# Generated by Django 4.2.3 on 2023-07-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(default='82', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='prodapp',
            field=models.TextField(default=''),
        ),
    ]
