# Generated by Django 4.2.3 on 2023-07-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
